apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: dra-tutorial
  labels:
    app: ollama-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama-deployment
  template:
    metadata:
      labels:
        app: ollama-deployment
    spec:
      containers:
      - name: ollama-deploy
        image: alpine/ollama:0.11.10
        resources:
          claims:
          - name: my-gpu-claim
      resourceClaims:
      - name: my-gpu-claim
        resourceClaimTemplateName: example-resource-claim-template