apiVersion: v1
kind: Pod
metadata:
  name: ollama
  namespace: dra-tutorial
  labels:
    app: pod
spec:
  containers:
  - name: ollama
    image: docker.io/alpine/ollama:0.12.9
    ports:
        - name: http
          containerPort: 11434
          protocol: TCP
    resources:
      claims:
      - name: gpu
    # requests:
      #  nvidia.com/gpu: "1"
  # tolerations:
  # - key: nvidia.com/gpu
    # effect: NoSchedule
    # operator: Exists
  resourceClaims:
  - name: gpu
    resourceClaimName: example-gpu