apiVersion: v1
kind: Pod
metadata:
  name: ollama2
  namespace: dra-tutorial
  labels:
    app: ollama2
spec:
  containers:
  - name: ollama2
    image: alpine/ollama:0.11.10
    ports:
        - name: http
          containerPort: 11434
          protocol: TCP
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    resourceClaimName: example-resource-claim