apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
 name: example-resource-claim-template
 namespace: dra-tutorial
spec:
  spec:
    devices:
      requests:
      - name: req-0
        firstAvailable:
        - name: more-than-40gi 
          deviceClassName: gpu.example.com
          allocationMode: ExactCount
          count: 1
          selectors:
          - cel:
              expression: |-
                device.capacity["gpu.example.com"].memory >= quantity("40Gi")
