apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
 name: example-resource-claim
 namespace: dra-tutorial
spec:
   devices:
     requests:
     - name: example-gpu
       deviceClassName: gpu.example.com
       selectors:
        - cel:
            expression: |-
              device.capacity["driver.example.com"].memory == quantity("80Gi")
