apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
 name: example-resource-claim
 namespace: dra-tutorial
spec:
   devices:
     requests:
     - name: example-gpu
       exactly:
         deviceClassName: gpu.example.com
         allocationMode: ExactCount
         count: 1
         selectors:
          - cel:
              expression: |-
                device.capacity["gpu.example.com"].memory == quantity("80Gi")
